{"tests": [{"name": "Basic Tests", "max_points": 10, "filename": "test_0", "points": 0, "files": [], "message": "'checkPalindrome()' looks good\n'checkPalindrome(a)' looks good\n'checkPalindrome(peak)' looks good\n'checkPalindrome(abc)' looks good\n'checkPalindrome(c al)' looks good\n'checkPalindrome(aabb)' looks good\n'checkPalindrome(abcdefghi)' looks good\n'checkPalindrome(palindrome)' looks good\nThe callable 'is_palindrome_all' supplied in your code failed with an exception while it was being called by the grading code:Traceback (most recent call last):\n  File \"/grade/run/code_feedback.py\", line 408, in call_user\n    return f(*args, **kwargs)\n  File \"<string>\", line 6, in is_palindrome_all\nNameError: name 'checkPalindrome' is not defined\n\n"}], "score": 0.0, "succeeded": true, "gradable": true, "max_points": 10, "images": []}